### PR TITLE
(docs): enable links to sections & fix links usage in markdown vars

### LINKED ISSUE #1460: (navigation): allow use # to navigate to specific part of page
### Description

for example

https://docs.ivy.app/onboarding/getting-started/installation#core_philosophy should open core philosophy section on https://docs.ivy.app/onboarding/getting-started/installation

Image

### Use Case

_No response_

### Proposed Solution

_No response_

### Alternatives Considered

_No response_

### Impact

_No response_

### Code Examples

```csharp

```

### Additional Context

_No response_

### LINKED ISSUE #4215: (markdown): links are not working
### Description

Markdown links are not working as expected. The links either do not render correctly or are not clickable.

Image

### PR DESCRIPTION
**Pull request by ArtemKhvorostianyi**
Handled dynamic section url visibility and enabled links to specific sections in docs:

https://github.com/user-attachments/assets/757d3eb0-a50a-4307-b273-c5dfb5a7febf

Also fixed issue #4215 where links supposed not to work if presented in single markdown var in layout.
Issue: links aren't clickable
Sollution: pass onLinkClick only when the widget actually subscribes to the event

https://github.com/user-attachments/assets/bb945cde-047c-4a85-8698-ff524394fd9e

### CODE REVIEW

**Comment by rorychatt** [comment]
I don't see the link update as I scroll

https://github.com/user-attachments/assets/ea5ce8f3-38fd-435c-aa8c-175d5c6baee7

**Comment by rorychatt** [comment]
all docs project should have this on for all headers we have

File: src/Ivy/Helpers/ValidationHelper.cs
Comment (rorychatt) [inline src/Ivy/Helpers/ValidationHelper.cs:1]: tests?

File: src/Ivy/AppShell/Shared.cs
Comment (rorychatt) [inline src/Ivy/AppShell/Shared.cs:1]: tests?

**Review by rorychatt — CHANGES_REQUESTED** [review]

File: src/frontend/src/lib/url.ts [hunk 1]
```diff
@@ -220,17 +220,25 @@ export function validateLinkUrl(url: string | null | undefined): string {
     return url;
   }
 
-  // Allow app:// URLs (Ivy internal navigation)
+  // Allow app:// URLs (Ivy internal navigation), including optional #fragment for article deep links
```
Comment (rorychatt) [inline src/frontend/src/lib/url.ts:231]: test

**Comment by ArtemKhvorostianyi** [comment]
Update url section visibility

https://github.com/user-attachments/assets/09af3f10-e3a1-47bb-95da-cea1cffd18f2


Covered with tests
Screenshot 2026-04-11 at 22 31 31

**Review by rorychatt — CHANGES_REQUESTED** [review]
still don't work

https://ivy-staging-docs-3817.sliplane.app/onboarding/getting-started/introduction#installing-the-cli

example: you don't open it and scroll to the right spot automatically.

test all cases.

**Comment by ArtemKhvorostianyi** [comment]
https://github.com/user-attachments/assets/ace4a65b-4dd8-4edc-865a-32aa9206c473

**Comment by artem-ivy-ai** [comment]
### Staging preview

**📄 Docs:** [https://ivy-staging-docs-3817.sliplane.app](https://ivy-staging-docs-3817.sliplane.app)
**🧪 Samples:** [https://ivy-staging-samples-3817.sliplane.app](https://ivy-staging-samples-3817.sliplane.app)

**Comment by artem-ivy-ai** [comment]
### Staging preview

**📄 Docs:** [https://ivy-staging-docs-3817.sliplane.app](https://ivy-staging-docs-3817.sliplane.app)
**🧪 Samples:** [https://ivy-staging-samples-3817.sliplane.app](https://ivy-staging-samples-3817.sliplane.app)

**Review by rorychatt — APPROVED** [review]

**Comment by artem-ivy-ai** [comment]
### Staging removed

Staging environment has been deleted for this PR.
