### PR TITLE
(fix): Fixed sidebar arrow for nested grouped items

### LINKED ISSUE #1949: (sidebar): arrow is not updating
### Description

Image

### PR DESCRIPTION
**Pull request by KaiserReich95**
Closes #1949 

https://github.com/user-attachments/assets/3cf09c5c-2d25-4e1c-8e12-b19a731cdbe8

### CODE REVIEW

File: frontend/src/widgets/layouts/sidebar/SidebarLayoutWidget.tsx [hunk 1]
```diff
@@ -203,7 +203,7 @@ const CollapsibleMenuItem: React.FC<{
   widgetId: string;
   level: number;
 }> = ({ item, eventHandler, widgetId, level }) => {
-  const [isOpen, setIsOpen] = useState(item.expanded);
+  const [isOpen, setIsOpen] = useState(item.expanded ?? false);
```
Comment (dcrjodle) [inline frontend/src/widgets/layouts/sidebar/SidebarLayoutWidget.tsx:206]: Is this needed?

Comment (rorychatt) [reply frontend/src/widgets/layouts/sidebar/SidebarLayoutWidget.tsx:206]: my guess is not really, but in case if this was null, sets it to false. But I think its okay here
