### PR TITLE
(datatable) fix: support theme

### LINKED ISSUE #1144: (datatable): theme awareness
### Description

Currently colors are hard-coded.

We need to make it theme aware, so different themes work with this, and don't forget about the dark theme too

### Steps to Reproduce

_No response_

### Expected Behavior

_No response_

### Actual Behavior

_No response_

### Environment

_No response_

### Code Samples

```csharp

```

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by dcrjodle**
closes #1144

### CODE REVIEW

File: frontend/src/widgets/dataTables/styles/theme.ts [hunk 1]
```diff
@@ -1,20 +1,45 @@
...
+      getCSSVariable('--foreground') || (isDark ? '#f8f8f8' : '#111827'),
+    textMedium:
+      getCSSVariable('--muted-foreground') || (isDark ? '#a1a1aa' : '#6b7280'),
+    textLight:
+      getCSSVariable('--muted-foreground') || (isDark ? '#71717a' : '#9ca3af'),
+    borderColor: 'transparent',
+    horizontalBorderColor:
+      getCSSVariable('--border') || (isDark ? '#404045' : '#d1d5db'),
+    linkColor: getCSSVariable('--accent') || (isDark ? '#26262b' : '#e5e7eb'),
+    cellHorizontalPadding: 16,
```
Comment (rorychatt) [inline frontend/src/widgets/dataTables/styles/theme.ts:43]: in the future, we might want to add .Size, and then these might not be good hard-coded values.

But this is not part of this issue

**Comment by rorychatt** [comment]
@claude review this
