### PR TITLE
(Card): Update Design of Metric Views

### LINKED ISSUE #1642: [MetricView]: need to be able to change height, it's hardcoded
### Description

Image

MetricView.cs

### Steps to Reproduce

_No response_

### Expected Behavior

_No response_

### Actual Behavior

_No response_

### Environment

_No response_

### Code Samples

```csharp

```

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by dcrjodle**
closes #1642 #1852 

- Simplify progress bar
- Solve bug where Card Icons where black
- Solve bug where Align overwrites Width
- Solve bug where Icon() extension created a Header that wasn't center aligned
- Add Extra Large text variant
- Refactor Card Widget to separate folder
Screenshot 2025-12-18 at 11 04 42

### CODE REVIEW

File: Ivy/Views/Dashboards/MetricView.cs [hunk 1]
```diff
@@ -15,8 +15,6 @@ public class MetricView(
     Func<Task<MetricRecord>> metricData
 ) : ViewBase
 {
-    private const int Height = 55;
```
Comment (rorychatt) [inline Ivy/Views/Dashboards/MetricView.cs:18]: the height constraint for metric views is now removed

**Review by rorychatt — APPROVED** [review]

**Comment by rorychatt** [comment]
Screenshot 2025-12-18 at 3 03 00 PM

Cards with details are misaligned now

**Comment by rorychatt** [comment]
Am I correct this also fixes #1852 ?

**Comment by dcrjodle** [comment]
@rorychatt yes it fixes 1852 as stated in the description

**Comment by rorychatt** [comment]
In Ivy-Open-Raise 

In the kanban with card builder, I see there is extra spacing for title, so it is not aligned with the action menu

Screenshot 2025-12-19 at 10 01 38 AM

For longer values, it get's cropped 

Screenshot 2025-12-19 at 10 00 46 AM

**Comment by dcrjodle** [comment]
@rorychatt pushed fix for wrapping content. Kanban Card Builder as a implementation question. I can make this work easily by
`new Card(header: Layout.Horizontal().Align(Align.Center)..., content: ..., footer: ...)`

**Comment by rorychatt** [comment]
this is how it is used in the open-raise example
```csharp  
return new Card(content)
                    .Small()
                    .Title(deal.InvestorName)
                    .Icon(dropDown)
                    .HandleClick(() => showEdit(deal.Id))
                    .Hover(CardHoverVariant.Pointer)
                    .Key(deal.Id);
                    
```

Looking at this example, I see that the Small() is not applied to the details. Is this a FE or a BE bug?

**Comment by rorychatt** [comment]
> @rorychatt pushed fix for wrapping content. Kanban Card Builder as a implementation question. I can make this work easily by `new Card(header: Layout.Horizontal().Align(Align.Center)..., content: ..., footer: ...)`

now sure what you meant here

**Comment by dcrjodle** [comment]
@rorychatt 
There are multiple ways to build your card. If you want to use extension methods solely, you can after my most recent commit, that changes the header builder to put titles and icons in one horizontal layout, and description below it

```
return new Card(content)
                .Small()
                .Title(Text.H4(deal.InvestorName))
                .Description(Text.Small("Description"))
                .Icon(dropDown)
                    
```

But you can also, as I mentioned, use the Card function parameters to build your card. The parameters are header, content, footer, then you can defined exactly how you want your Card

**Comment by rorychatt** [comment]
@dcrjodle let me know when I should review this so we merge your stuff
